"""Shared schemas module."""

from shared.schemas.schemas import (
    AISuggestionResponse,
    AlertEvent,
    APIResponse,
    ArtifactsConfig,
    CacheConfig,
    EnrichedLogEvent,
    ErrorDetail,
    JobConfig,
    JobEventMessage,
    JobResponse,
    LogErrorEvent,
    NotificationConfigCreate,
    NotificationConfigResponse,
    NotificationConfigUpdate,
    OrganizationCreate,
    OrganizationResponse,
    OTPStatusResponse,
    PaginationMeta,
    PipelineCreate,
    PipelineListResponse,
    PipelineResponse,
    PipelineTriggerEvent,
    PipelineUpdate,
    PipelineYAMLConfig,
    RawLogEvent,
    RepositoryCreate,
    RepositoryResponse,
    ResendOTPRequest,
    RetryConfig,
    RuleConfig,
    SecurityFindingResponse,
    SecurityPolicyCreate,
    SecurityPolicyResponse,
    SecurityPolicyUpdate,
    SecuritySummary,
    SendOTPRequest,
    SendOTPResponse,
    SuppressFindingRequest,
    TokenRefreshRequest,
    TokenResponse,
    UserCreate,
    UserLogin,
    UserResponse,
    VerifyOTPRequest,
    VerifyOTPResponse,
    VoteSuggestionRequest,
    WebhookResponse,
)

__all__ = [
    # Generic
    "APIResponse",
    "ErrorDetail",
    "PaginationMeta",
    # Webhook
    "PipelineTriggerEvent",
    "WebhookResponse",
    # Pipeline
    "PipelineCreate",
    "PipelineUpdate",
    "PipelineResponse",
    "PipelineListResponse",
    "PipelineYAMLConfig",
    # Job
    "JobConfig",
    "JobResponse",
    "JobEventMessage",
    "RetryConfig",
    "ArtifactsConfig",
    "CacheConfig",
    "RuleConfig",
    # Log
    "RawLogEvent",
    "EnrichedLogEvent",
    "LogErrorEvent",
    # Security
    "SecurityFindingResponse",
    "SecuritySummary",
    "SuppressFindingRequest",
    "SecurityPolicyCreate",
    "SecurityPolicyUpdate",
    "SecurityPolicyResponse",
    # Notification
    "AlertEvent",
    "NotificationConfigCreate",
    "NotificationConfigUpdate",
    "NotificationConfigResponse",
    # AI
    "AISuggestionResponse",
    "VoteSuggestionRequest",
    # Auth
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "TokenResponse",
    "TokenRefreshRequest",
    # OTP Auth
    "SendOTPRequest",
    "SendOTPResponse",
    "VerifyOTPRequest",
    "VerifyOTPResponse",
    "ResendOTPRequest",
    "OTPStatusResponse",
    # Repository
    "RepositoryCreate",
    "RepositoryResponse",
    # Organization
    "OrganizationCreate",
    "OrganizationResponse",
]
